version: "3"

services:
  db: 
    container_name: db
    build: 
      context: .
      dockerfile: compose/db/Dockerfile
    env_file:
      - compose/db/db.env
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql

  db-manager:
    image: adminer:4.7
    container_name: db-manager
    restart: always
    ports:
      - 8081:8080

  webserver:
    container_name: webserver
    image: nginx:latest
  
  webapp:
    image: mailyc/doudizhu:latest
    container_name: webapp
    build: 
      context: .
      dockerfile: compose/app/Dockerfile
    command: ["python3", "app.py"]
    env_file:
      - compose/db/db.env
    networks:
      - default
    ports:
      - 8080:8080
    volumes:
      - /var/log:/var/log
      - ./doudizhu:/app
    restart: always

networks:
  default:
    driver: bridge

volumes: 
  data: